name: Release Runner

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: oevent-course-helper-arc-runner 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Ensure Tag is on Main
        run: ensure-main.sh

      - name: Validate Increasing Version
        run: validate-increasing-version.sh

      - name: Set Clean Version
        shell: bash
        run: set-clean-version.sh

      - name: Authenticate with NuGet.org
        uses: NuGet/login@v1
        id: nuget_login
        with:
          user: RasmusSteen

      - name: Restore Dependencies
        run: dotnet restore -p:Version=${{ env.SEMVER }}

      - name: Generate ThirdPartyNotices
        run: |
          dotnet run --project ./GenerateThirdPartyNotices/GenerateThirdPartyNotices.csproj \
          -p:Version=${{ env.SEMVER }} \
          -- \
          ./OEventCourseHelper/obj/project.assets.json \
          ./ThirdPartyNotices.txt \
          ./Licenses

      - name: Build
        run: dotnet build --no-restore -p:Version=${{ env.SEMVER }}

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal -p:Version=${{ env.SEMVER }}

      - name: Build and Zip All Platforms
        run: |
          RIDS=("win-x64" "win-x86" "linux-x64")
          
          for RID in "${RIDS[@]}"; do
            echo "Publishing for $RID..."
            
            dotnet publish OEventCourseHelper/OEventCourseHelper.csproj \
              -c Release \
              -r $RID \
              --self-contained false \
              -p:PublishSingleFile=false \
              -p:Version=${{ env.SEMVER }} \
              -o ./publish_$RID

            cp ./ThirdPartyNotices.txt ./publish_$RID/
            cp ./README.md ./publish_$RID/
            cp ./LICENSE ./publish_$RID/LICENSE.txt
            
            zip -j OEventCourseHelper-${{ env.VERSION }}-$RID.zip ./publish_$RID/*
          done

      - name: Pack OEventCourseHelper.Core
        run: dotnet pack OEventCourseHelper.Core/OEventCourseHelper.Core.csproj -c Release -o ./nupkg -p:Version=${{ env.SEMVER }}

      - name: Publish OEventCourseHelper.Core to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.nuget_login.outputs.NUGET_API_KEY }} --skip-duplicate

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            **NuGet Package:** [OEventCourseHelper.Core ${{ env.SEMVER }}](https://www.nuget.org/packages/OEventCourseHelper.Core/${{ env.SEMVER }})
          files: OEventCourseHelper-${{ env.VERSION }}-*.zip
          generate_release_notes: true